### ISSUE TITLE
UDUnits functionality broken

### ISSUE THREAD

**Issue by tsjackson-noaa** [conda-forge/nco-feedstock#103] opened 2020-01-28 19:25 UTC
Issue: 
Recent versions of NCO utilities installed through Anaconda function correctly, but throw an error when performing any operation requiring functionality that uses the UDUnits library (at least, relating to calendar functions.)

I've verified this with Anaconda nco 4.7.6, 4.8.1 and 4.9.1, with 64-bit offset and NetCDF4-Classic files, and with conda 4.7.12 and 4.8.1.

Thanks!
Tom Jackson, GFDL/NOAA

Steps to reproduce:
I believe the following should happen for any netcdf test file; please let me know if you can't reproduce it:
```
$ conda create -n nco_test -c conda-forge nco
$ conda activate nco_test
$ which ncks
/local2/home/anaconda2/envs/nco_test/bin/ncks
$ ncks -m -v time <test_file.nc>
# works correctly; following is from my test file
netcdf atmos_cmip.200001-200412.pr {
  dimensions:
    bnds = 2 ;
    time = UNLIMITED ; // (60 currently)

  variables:
    double time(time) ;
      time:long_name = "time" ;
      time:units = "days since 1850-01-01 00:00:00" ;
      time:axis = "T" ;
      time:calendar_type = "NOLEAP" ;
      time:calendar = "noleap" ;
      time:bounds = "time_bnds" ;

    double time_bnds(time,bnds) ;
      time_bnds:long_name = "time axis boundaries" ;
      time_bnds:units = "days since 1850-01-01 00:00:00" ;
      time_bnds:missing_value = 1.e+20 ;
      time_bnds:_FillValue = 1.e+20 ;
} // group /
# believe this can be any command that uses UDUnits conversion
$ ncks -d time,'2002-01-01','2003-01-01' <test_file.nc> out.nc
ncks: nco_cln_prs_tm() failed to initialize UDUnits2 library
ncks: ERROR nco_cln_clc_dbl_org(): report unt_sng=2002-01-01 bs_sng=days since 1850-01-01 00:00:00 calendar=5 og_val=0.000000
```
Googling the error message doesn't yield anything useful. Anaconda has installed udunits2 (see conda list below), and it's linked correctly (ldd output below):
<details>

```
$ ldd `which ncks`
        linux-vdso.so.1 =>  (0x00007ffc3979e000)
        libnco-4.9.1.so => /local2/home/anaconda2/envs/nco_test/bin/../lib/libnco-4.9.1.so (0x00002b1e2a2c6000)
        libnetcdf.so.15 => /local2/home/anaconda2/envs/nco_test/bin/../lib/libnetcdf.so.15 (0x00002b1e2a4b7000)
        libgomp.so.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/libgomp.so.1 (0x00002b1e2a3eb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b1e2a603000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b1e2a81f000)
        libexpat.so.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libexpat.so.1 (0x00002b1e2a456000)
        libcurl.so.4 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libcurl.so.4 (0x00002b1e2abed000)
        libgsl.so.23 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libgsl.so.23 (0x00002b1e2ac73000)
        libcblas.so.3 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libcblas.so.3 (0x00002b1e2af1c000)
        libudunits2.so.0 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libudunits2.so.0 (0x00002b1e2a48b000)
        libstdc++.so.6 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libstdc++.so.6 (0x00002b1e2cad5000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b1e2cc49000)
        libgcc_s.so.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libgcc_s.so.1 (0x00002b1e2cf4b000)
        libmfhdf.so.0 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libmfhdf.so.0 (0x00002b1e2cf5f000)
        libdf.so.0 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libdf.so.0 (0x00002b1e2cf8b000)
        libhdf5_hl.so.100 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libhdf5_hl.so.100 (0x00002b1e2d03a000)
        libhdf5.so.103 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libhdf5.so.103 (0x00002b1e2d060000)
        libmpi.so.12 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./libmpi.so.12 (0x00002b1e2d42d000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b1e2d752000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b1e2d95a000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b1e2a293000)
        libssh2.so.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libssh2.so.1 (0x00002b1e2db5e000)
        libssl.so.1.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libssl.so.1.1 (0x00002b1e2db91000)
        libcrypto.so.1.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libcrypto.so.1.1 (0x00002b1e2dc21000)
        libgssapi_krb5.so.2 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libgssapi_krb5.so.2 (0x00002b1e2decf000)
        libkrb5.so.3 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libkrb5.so.3 (0x00002b1e2df1e000)
        libk5crypto.so.3 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libk5crypto.so.3 (0x00002b1e2dff5000)
        libcom_err.so.3 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libcom_err.so.3 (0x00002b1e2e014000)
        libz.so.1 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libz.so.1 (0x00002b1e2e01a000)
        libgfortran.so.4 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libgfortran.so.4 (0x00002b1e2e034000)
        libjpeg.so.9 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libjpeg.so.9 (0x00002b1e2e162000)
        libquadmath.so.0 => /local2/home/anaconda2/envs/nco_test/bin/../lib/././libquadmath.so.0 (0x00002b1e2e1a0000)
        libkrb5support.so.0 => /local2/home/anaconda2/envs/nco_test/bin/../lib/./././libkrb5support.so.0 (0x00002b1e2e1da000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00002b1e2e1e8000)

```
</details>
Anaconda doesn't set LD_LIBRARY_PATH, but I've verified that adding the environment's /lib to this environment variable doesn't change the error.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /local2/home/anaconda2/envs/nco_test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
esmf                      8.0.0           mpi_mpich_h06e08bd_104    conda-forge
expat                     2.2.9                he1b5a44_0    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          mpi_mpich_ha7d0aea_1004    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.3           mpi_mpich_h755db7c_1    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
nco                       4.9.1           mpi_mpich_h58f0b72_100    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.5.2           mpi_mpich_hd560429_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
tempest-remap             2.0.3           mpi_mpich_h21555f6_7    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : nco_test
    active env location : /local2/home/anaconda2/envs/nco_test
            shell level : 1
       user config file : /home/Thomas.Jackson/.condarc
 populated config files : 
          conda version : 4.8.1
    conda-build version : 3.18.7
         python version : 2.7.16.final.0
       virtual packages : __glibc=2.17
       base environment : /local2/home/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /local2/home/anaconda2/pkgs
                          /home/Thomas.Jackson/.conda/pkgs
       envs directories : /local2/home/anaconda2/envs
                          /home/Thomas.Jackson/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.1 requests/2.21.0 CPython/2.7.16 Linux/3.10.0-1062.9.1.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 20470:70
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment] 2020-01-28 19:42
I have the same packages but I could not reproduce this with a netCDF file I used to test this.

**Comment by czender** [comment] 2020-01-28 20:44
Could still be an `LD_LIBRARY_PATH` issue, prepend the Anaconda library path to yours or else `UDUNITS` may come from an incompatible elsewhere.

**Comment by tsjackson-noaa** [comment] 2020-01-28 21:16
Wow, thanks for getting back to me so quickly! Based on @ocefpaf 's comment, I found the source of the problem: everything works under bash, but in tcsh (don't ask; I was using it for historical compatibility with our systems) Conda didn't set the UDUNITS2_XML_PATH environment variable. Doing
```
setenv UDUNITS2_XML_PATH "$CONDA_PREFIX/share/udunits/udunits2.xml"
```
in tcsh after activating the environment resolved the problem.

Since the issue is due to Anaconda's spotty tcsh support and not the NCO distribution (the variable is set properly on bash/zsh), I'll close the issue. Thanks again for your help!

**Comment by ocefpaf** [comment] 2020-01-28 21:20
Let's keep this open now that we know the problem. We should provide more options on the activation script to cover tcsh and others.

**Comment by xylar** [comment] 2020-01-28 21:28
@tsjackson-noaa, thanks for figuring this one out.  It should be easy enough to fix the activation scripts.  @ocefpaf, if you don't get to it, I'll try to do so soon.

**Comment by xylar** [comment] 2020-01-28 21:31
Since the problem is actually with udunits2 and not with NCO itself, I opened an issue there, too.

**Comment by ocefpaf** [comment] 2020-01-28 23:34
> @ocefpaf, if you don't get to it, I'll try to do so soon.

If you know what to do wand are willing to do please go ahead. I'm working just a few hours a day. (Slowly recovery from a knee surgery.)

**Comment by ocefpaf** [comment] 2020-01-28 23:35
Closing in favor of https://github.com/conda-forge/udunits2-feedstock/issues/30.

(Thanks @xylar!)

**Closed by ocefpaf** 2020-01-28 23:35 UTC
